# :::::::::::::::::::
# Default section
# :::::::::::::::::::
default:
  # Batch size of files to get in one request
  BATCH_COUNT : 100
  # Limit Total number of files
  TOTAL_COUNT_LIMIT : 10000

# :::::::::::::::::::
# Parallel processing
# :::::::::::::::::::
  NUM_CPU : 4
  PARALLEL : False

# :::::::::::::::::::
# Directories
# :::::::::::::::::::
  LOG_PATH : ''
  SIGNAL_PATH : 'data/ELPP_files'
  PRODUCT_PATH : 'data/ELDAmwl_files'
  TEMP_PATH : ''
  PLUGINS_DIR : ''

# :::::::::::::::::::
# database connection
# :::::::::::::::::::
#  DB_SERVER : ''
#  DB_USER : ''
#  DB_PASS : ''
#  DB_DB : ''
# You have to supply a .secrets.yaml file beside this file with the database access secrets shown above!

# :::::::::::::::::::
# Logging
# :::::::::::::::::::

  # The logfiles
  # general log level
  log_level : DEBUG
  # The desired log_level for console output
  log_level_console : DEBUG
  # The desired log_level for the logfile
  log_level_file : INFO
  # Colors for the log console output (Options see color_log-package)
  log_colors : {
      'DEBUG': 'cyan',
      'INFO': 'green',
      'WARNING': 'yellow',
      'ERROR': 'red',
      'CRITICAL': 'red,bg_white',
  }

  WRITE_EXTENDED_OUTPUT : True
  APPEND_LOG_FILE : False
